FROM node:20

WORKDIR /app

COPY package.json ./

COPY yarn.lock ./

RUN yarn

COPY . .

RUN npx prisma generate

RUN yarn build

CMD ["sh", "-c", "yarn prisma migrate deploy && yarn init:wallets && yarn start:prod"]
